version: 1.0

name: build-unzip-deploy-to-s3

on:
  push:
    branches:
      - main

steps:
  - name: Install dependencies
    run: npm install

  - name: Build project
    run: npm run build

  - name: Zip build folder
    run: |
      cd build
      zip -r ../build.zip .
      cd ..

  - name: Unzip build.zip
    run: |
      mkdir unzipped
      unzip build.zip -d unzipped

  - name: Upload unzipped files to S3
    run: |
      aws s3 sync unzipped/ s3://apilambada/ --delete --region us-east-2
    env:
      AWS_ACCESS_KEY_ID: $AKIAXWAJSPI2SNMO25UM
      AWS_SECRET_ACCESS_KEY: $lhoLsmXg37mgvgv/LwiTWDJAcSA0uGbXJ5C3Brm6
      AWS_DEFAULT_REGION: us-east-1

  - name: Cleanup
    run: rm -rf build.zip unzipped
